tasks:
  Hitsugi no Chaika:
    series: 
    - Hitsugi no Chaika
    rss: http://www.nyaa.se/?page=rss&user=176350&term=Chaika
    quality:
      - 720p
    transmission:
      host: localhost
      port: 9091
      path: "~/Torrents/Airing/Hitsugi\ no\ Chaika"
  
  Kanojo ga Flag wo Oraretara:  
    series:
    - Kanojo ga Flag wo Oraretara 
    rss: http://www.nyaa.se/?page=rss&user=265&term=Kanojo+ga+Flag+wo+Oraretara    
    transmission:
      host: localhost
      port: 9091
      path: "~/Torrents/Airing/Kanojo\ ga\ Flag\ wo\ Oraretara"
    
  Mekakucity Actors:
    series:  
    - Mekakucity Actors 
    rss: http://www.nyaa.se/?page=rss&user=139889&term=Mekakucity+Actors    
    transmission:
      host: localhost
      port: 9091
      path: "~/Torrents/Airing/Mekakucity\ Actors"
